import connectDB from "../config/db.mjs";
import Products from "../models/product.model.mjs";

const Products = [
    // ===== KIDS =====
    {
        name: "Kids Summer Lookbook Set",
        price: 132.49,
        discount: 0,
        category: "kids",
        stock: 120,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://i.pinimg.com/1200x/fb/81/5b/fb815b8be4584e4bec3c66a0730c141c.jpg",
        comments: [],
    },
    {
        name: "Kids Casual Sports Retro Set",
        price: 220.72,
        discount: 0,
        category: "kids",
        stock: 100,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://i.pinimg.com/1200x/81/f4/2c/81f42ceb7efb423fd59cf6c164fdad8b.jpg",
        comments: [],
    },
    {
        name: "Kids Graphic T-Shirt",
        price: 24.99,
        discount: 0,
        category: "kids",
        stock: 180,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea",
        comments: [],
    },
    {
        name: "Kids Denim Jacket",
        price: 49.99,
        discount: 0,
        category: "kids",
        stock: 75,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf",
        comments: [],
    },
    {
        name: "Kids Cartoon Print Hoodie",
        price: 34.99,
        discount: 0,
        category: "kids",
        stock: 150,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf",
        comments: [],
    },
    {
        name: "Kids Color Block T-Shirt",
        price: 19.99,
        discount: 0,
        category: "kids",
        stock: 200,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1",
        comments: [],
    },
    {
        name: "Kids Denim Overalls",
        price: 44.99,
        discount: 0,
        category: "kids",
        stock: 90,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
        comments: [],
    },
    {
        name: "Kids Striped Pajama Set",
        price: 29.99,
        discount: 0,
        category: "kids",
        stock: 140,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1603252109303-2751441dd157",
        comments: [],
    },
    {
        name: "Kids Winter Puffer Jacket",
        price: 59.99,
        discount: 0,
        category: "kids",
        stock: 70,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1602810318355-7c6b9d901609",
        comments: [],
    },
    {
        name: "Kids Rainbow Hoodie",
        price: 32.99,
        discount: 0,
        category: "kids",
        stock: 110,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1543852786-1cf6624b9987",
        comments: [],
    },
    {
        name: "Kids Sports Jogger Pants",
        price: 27.99,
        discount: 0,
        category: "kids",
        stock: 160,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2",
        comments: [],
    },
    {
        name: "Kids Cartoon Pajama Set",
        price: 31.99,
        discount: 0,
        category: "kids",
        stock: 130,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1585386959984-a41552231693",
        comments: [],
    },
    {
        name: "Kids Polka Dot Dress",
        price: 36.99,
        discount: 0,
        category: "kids",
        stock: 95,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea",
        comments: [],
    },
    {
        name: "Kids Denim Shorts",
        price: 22.99,
        discount: 0,
        category: "kids",
        stock: 175,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
        comments: [],
    },
    {
        name: "Kids Cartoon Sneakers",
        price: 39.99,
        discount: 0,
        category: "kids",
        stock: 120,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1",
        comments: [],
    },
    {
        name: "Kids Cozy Knit Sweater",
        price: 33.99,
        discount: 0,
        category: "kids",
        stock: 100,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2",
        comments: [],
    },
    {
        name: "Kids Printed Rain Jacket",
        price: 41.99,
        discount: 0,
        category: "kids",
        stock: 85,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf",
        comments: [],
    },
    {
        name: "Kids Soft Cotton Shorts Set",
        price: 26.99,
        discount: 0,
        category: "kids",
        stock: 190,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1585386959984-a41552231693",
        comments: [],
    },
    {
        name: "Kids Party Wear Dress",
        price: 54.99,
        discount: 0,
        category: "kids",
        stock: 60,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1543852786-1cf6624b9987",
        comments: [],
    },
    {
        name: "Kids Superhero T-Shirt",
        price: 21.99,
        discount: 0,
        category: "kids",
        stock: 220,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
        comments: [],
    },
    {
        name: "Kids Lightweight Windbreaker",
        price: 47.99,
        discount: 0,
        category: "kids",
        stock: 90,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1602810318355-7c6b9d901609",
        comments: [],
    },
    {
        name: "Kids Classic Polo Shirt",
        price: 28.99,
        discount: 0,
        category: "kids",
        stock: 170,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1",
        comments: [],
    },
    {
        name: "Kids Summer Beach Outfit",
        price: 35.99,
        discount: 0,
        category: "kids",
        stock: 140,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1603252109303-2751441dd157",
        comments: [],
    },
    {
        name: "Kids Cozy Sleepwear Set",
        price: 30.99,
        discount: 0,
        category: "kids",
        stock: 160,
        deal: false,
        orderCount: 0,
        sizes: ["XS", "S", "M", "L"],
        imageUrl: "https://images.unsplash.com/photo-1585386959984-a41552231693",
        comments: [],
    },
    // ===== MEN =====
    {
        name: "Men Palm Tree Print Shirt",
        price: 72.98,
        discount: 0,
        category: "men",
        stock: 173,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://i.pinimg.com/1200x/0b/47/65/0b4765ba5135bd6a6b1f349743265745.jpg",
        comments: [],
    },
    {
        name: "Men Beach Leisure Set",
        price: 49.32,
        discount: 0,
        category: "men",
        stock: 193,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://img.fantaskycdn.com/b5fe27368d62945371392dc54895c02b_1024x.webp",
        comments: [],
    },
    {
        name: "Men Summer Casual Outfit",
        price: 53.02,
        discount: 0,
        category: "men",
        stock: 143,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://i.pinimg.com/736x/9c/29/7a/9c297a4dcb62fe39db64470255f66c55.jpg",
        comments: [],
    },
    {
        name: "Men Korean Style Striped Shirt",
        price: 29.90,
        discount: 0,
        category: "men",
        stock: 813,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://kroyy.com/cdn/shop/files/H7ca130d2dc3543139176644ce7101cc7q.jpg?v=1727085855",
        comments: [],
    },
    {
        name: "Men Black Striped Shirt",
        price: 29.90,
        discount: 0,
        category: "men",
        stock: 347,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://i.pinimg.com/736x/d1/c6/57/d1c657b131e571001fb4d513549b6082.jpg",
        comments: [],
    },
    {
        name: "Men Old Money Casual Outfit",
        price: 123.54,
        discount: 0,
        category: "men",
        stock: 243,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://i.pinimg.com/736x/68/75/09/68750924aefa6660cf80bd73888f8915.jpg",
        comments: [],
    },
    {
        name: "Men Old Money Casual Jacket",
        price: 123.54,
        discount: 0,
        category: "men",
        stock: 243,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://i.pinimg.com/736x/ed/52/82/ed528238aca86bbaecb0e10b862095ae.jpg",
        comments: [],
    },
    {
        name: "Men Slim Fit Denim Jeans",
        price: 64.99,
        discount: 0,
        category: "men",
        stock: 190,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1542272604-787c3835535d",
        comments: [],
    },
    {
        name: "Men Classic White Sneakers",
        price: 89.99,
        discount: 0,
        category: "men",
        stock: 130,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1528701800489-20be3c85fdb1",
        comments: [],
    },
    {
        name: "Women Floral Summer Dress",
        price: 54.99,
        discount: 0,
        category: "women",
        stock: 180,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
        comments: [],
    },
    {
        name: "Women Casual Linen Shirt",
        price: 39.99,
        discount: 0,
        category: "women",
        stock: 210,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3",
        comments: [],
    },
    {
        name: "Women High Waist Denim Jeans",
        price: 69.99,
        discount: 0,
        category: "women",
        stock: 160,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246",
        comments: [],
    },
    {
        name: "Women Elegant Maxi Dress",
        price: 89.99,
        discount: 0,
        category: "women",
        stock: 95,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956",
        comments: [],
    },
    {
        name: "Women Casual Knit Sweater",
        price: 44.99,
        discount: 0,
        category: "women",
        stock: 175,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
        comments: [],
    },
    {
        name: "Women Slim Fit Blazer",
        price: 99.99,
        discount: 0,
        category: "women",
        stock: 85,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1520975698519-59c09f06b7c8",
        comments: [],
    },
    {
        name: "Women Pleated Midi Skirt",
        price: 49.99,
        discount: 0,
        category: "women",
        stock: 140,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
        comments: [],
    },
    {
        name: "Women Soft Cotton T-Shirt",
        price: 24.99,
        discount: 0,
        category: "women",
        stock: 260,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1520974735194-6c5cdb1d94a6",
        comments: [],
    },
    {
        name: "Women Classic White Sneakers",
        price: 84.99,
        discount: 0,
        category: "women",
        stock: 130,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2",
        comments: [],
    },
    {
        name: "Women Lightweight Cardigan",
        price: 42.99,
        discount: 0,
        category: "women",
        stock: 190,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2",
        comments: [],
    },
    {
        name: "Women Satin Evening Top",
        price: 59.99,
        discount: 0,
        category: "women",
        stock: 110,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956",
        comments: [],
    },
    {
        name: "Women Casual Wide Leg Pants",
        price: 64.99,
        discount: 0,
        category: "women",
        stock: 150,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246",
        comments: [],
    },
    {
        name: "Women Printed Chiffon Blouse",
        price: 46.99,
        discount: 0,
        category: "women",
        stock: 170,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3",
        comments: [],
    },
    {
        name: "Women Casual Denim Jacket",
        price: 89.99,
        discount: 0,
        category: "women",
        stock: 100,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
        comments: [],
    },
    {
        name: "Women Elegant Party Gown",
        price: 129.99,
        discount: 0,
        category: "women",
        stock: 60,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e",
        comments: [],
    },
    {
        name: "Women Casual Lounge Set",
        price: 58.99,
        discount: 0,
        category: "women",
        stock: 155,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1520974735194-6c5cdb1d94a6",
        comments: [],
    },
    {
        name: "Women Trendy Crop Top",
        price: 29.99,
        discount: 0,
        category: "women",
        stock: 230,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2",
        comments: [],
    },
    {
        name: "Women Office Wear Pencil Skirt",
        price: 52.99,
        discount: 0,
        category: "women",
        stock: 140,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
        comments: [],
    },
    {
        name: "Women Casual Hooded Sweatshirt",
        price: 47.99,
        discount: 0,
        category: "women",
        stock: 190,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2",
        comments: [],
    },
    {
        name: "Women Summer Beach Dress",
        price: 61.99,
        discount: 0,
        category: "women",
        stock: 120,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
        comments: [],
    },
    // ===== WOMEN =====
    {
        name: "Women Old Money Casual Outfit",
        price: 90.99,
        discount: 0,
        category: "women",
        stock: 357,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://i.pinimg.com/736x/2f/db/6a/2fdb6a0142b3ebcdd53357ce01a14364.jpg",
        comments: [],
    },
    {
        name: "Women Celine Style Outfit Set",
        price: 123.54,
        discount: 0,
        category: "women",
        stock: 243,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://i.pinimg.com/1200x/57/0b/2a/570b2a9e2fdb784121603efebcec9d32.jpg",
        comments: [],
    },
    {
        name: "Women Summer Floral Dress",
        price: 49.99,
        discount: 0,
        category: "women",
        stock: 210,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1520975916090-3105956dac38",
        comments: [],
    },
    {
        name: "Women Elegant Handbag",
        price: 69.99,
        discount: 0,
        category: "women",
        stock: 95,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1584917865442-de89df76afd3",
        comments: [],
    },
    {
        name: "Women High Heel Sandals",
        price: 79.99,
        discount: 0,
        category: "women",
        stock: 85,
        deal: false,
        orderCount: 0,
        sizes: ["S", "M", "L", "XL"],
        imageUrl: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2",
        comments: [],
    },
    {
        name: "Men Classic Cotton T-Shirt",
        price: 24.99,
        discount: 0,
        category: "men",
        stock: 260,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
        comments: [],
    },
    {
        name: "Men Casual Linen Shirt",
        price: 39.99,
        discount: 0,
        category: "men",
        stock: 210,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3",
        comments: [],
    },
    {
        name: "Men Slim Fit Denim Jeans",
        price: 69.99,
        discount: 0,
        category: "men",
        stock: 180,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1542272604-787c3835535d",
        comments: [],
    },
    {
        name: "Men Formal Office Shirt",
        price: 49.99,
        discount: 0,
        category: "men",
        stock: 150,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
        comments: [],
    },
    {
        name: "Men Casual Hoodie",
        price: 44.99,
        discount: 0,
        category: "men",
        stock: 170,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2",
        comments: [],
    },
    {
        name: "Men Winter Puffer Jacket",
        price: 109.99,
        discount: 0,
        category: "men",
        stock: 90,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1602810318355-7c6b9d901609",
        comments: [],
    },
    {
        name: "Men Casual Polo Shirt",
        price: 34.99,
        discount: 0,
        category: "men",
        stock: 220,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1598033129183-c4f50c736f10",
        comments: [],
    },
    {
        name: "Men Classic Leather Jacket",
        price: 149.99,
        discount: 0,
        category: "men",
        stock: 60,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1551028719-00167b16eac5",
        comments: [],
    },
    {
        name: "Men Sports Tracksuit Set",
        price: 89.99,
        discount: 0,
        category: "men",
        stock: 140,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1528701800489-20be3c85fdb1",
        comments: [],
    },
    {
        name: "Men Lightweight Windbreaker",
        price: 74.99,
        discount: 0,
        category: "men",
        stock: 120,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
        comments: [],
    },
    {
        name: "Men Casual Cargo Pants",
        price: 59.99,
        discount: 0,
        category: "men",
        stock: 160,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2",
        comments: [],
    },
    {
        name: "Men Formal Suit Blazer",
        price: 189.99,
        discount: 0,
        category: "men",
        stock: 70,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1520975698519-59c09f06b7c8",
        comments: [],
    },
    {
        name: "Men Casual Denim Jacket",
        price: 94.99,
        discount: 0,
        category: "men",
        stock: 110,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
        comments: [],
    },
    {
        name: "Men Cotton Jogger Pants",
        price: 49.99,
        discount: 0,
        category: "men",
        stock: 190,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2",
        comments: [],
    },
    {
        name: "Men Classic Oxford Shirt",
        price: 54.99,
        discount: 0,
        category: "men",
        stock: 175,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3",
        comments: [],
    },
    {
        name: "Men Summer Beach Outfit",
        price: 62.99,
        discount: 0,
        category: "men",
        stock: 145,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
        comments: [],
    },
    {
        name: "Men Casual Sports Shorts",
        price: 29.99,
        discount: 0,
        category: "men",
        stock: 230,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2",
        comments: [],
    },
    {
        name: "Men Classic Running Shoes",
        price: 99.99,
        discount: 0,
        category: "men",
        stock: 135,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1528701800489-20be3c85fdb1",
        comments: [],
    },
    {
        name: "Men Casual Checkered Shirt",
        price: 45.99,
        discount: 0,
        category: "men",
        stock: 165,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3",
        comments: [],
    },
    {
        name: "Men Premium Wool Coat",
        price: 179.99,
        discount: 0,
        category: "men",
        stock: 55,
        deal: false,
        orderCount: 0,
        sizes: ["M", "L", "XL", "2XL"],
        imageUrl: "https://images.unsplash.com/photo-1602810318355-7c6b9d901609",
        comments: [],
    },
];


// Function to add products in shoppey(store) not used only for seeding but also for adding products in future
// Not recomented to touch or modify that file as it is used for seeding products in database and also for adding products in future
const products = async () => {
    try {
        await connectDB();
        await Products.deleteMany();
        await Products.insertMany(Products);
        console.log("Products seeded successfully.");
        process.exit(1);
    } catch (error) {
        console.log("Error while seeding products:", error);
        process.exit(1);
    }
}

// Call the function to seed products if needed products();
products();