import './App.css';
import { React, lazy, Suspense } from 'react';
import { Routes, Route } from 'react-router-dom';

// Lazy load components
const Landing = lazy(() => import('./components/Landing.jsx'));
const Discount = lazy(() => import('./components/Discount.jsx'));
const Collection = lazy(() => import('./components/newCollection.jsx'));
const BestSeller = lazy(() => import('./components/BestSeller.jsx'));
const Deal = lazy(() => import('./components/Deal.jsx'));
const Product = lazy(() => import('./components/Product.jsx'));
const About = lazy(() => import('./components/About.jsx'));
const Social = lazy(() => import('./components/Social.jsx'));
const SignIU = lazy(() => import('./components/SignIU.jsx'));
const AllProducts = lazy(() => import('./components/AllProducts.jsx'));
const ProductDetail = lazy(() => import('./components/ProductDetail.jsx'));
const Cart = lazy(() => import('./components/Cart.jsx'));
const Save = lazy(() => import('./components/Save.jsx'));

export const Products = [
  {
    id: 1,
    name: "Reversible Silk-Linen Blazer Dress",
    price: 189.99,
    size: "S",
    src: 'assets/w1.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: false,
    deal: true,
    collection: 2025
  },
  {
    id: 2,
    name: "Holographic Midi Skirt with Slit",
    price: 129.50,
    size: "M",
    src: 'assets/w2.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 3,
    name: "Bio-Deodorizing Yoga Set",
    price: 98.99,
    size: "L",
    src: 'assets/w3.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 4,
    name: "Convertible Cashmere Wrap",
    price: 159.99,
    size: "One Size",
    src: 'assets/w4.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 5,
    name: "Architectural Buckle Ankle Boots",
    price: 219.99,
    size: "US8",
    src: 'assets/w5.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: false,
    deal: false,
    collection: 2024
  },
  {
    id: 6,
    name: "Temperature-Regulating Silk Camisole",
    price: 79.99,
    size: "XS",
    src: 'assets/w6.webp',
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 7,
    name: "Origami Fold Leather Tote",
    price: 349.99,
    size: "One Size",
    src: 'assets/w7.webp',
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 8,
    name: "Glow-in-the-Dark Evening Gown",
    price: 279.99,
    size: "6",
    src: 'assets/w8.webp',
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: true,
    collection: 2024
  },
  {
    id: 9,
    name: "Self-Cleaning Wide-Leg Pants",
    price: 139.99,
    size: "27",
    src: 'assets/w9.webp',
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 10,
    name: "Customizable Birthstone Necklace",
    price: 149.99,
    size: "Adjustable",
    src: 'assets/w10.webp',
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 11,
    name: "Recycled Sari Silk Kimono",
    price: 89.99,
    size: "M/L",
    src: 'assets/w11.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: false,
    deal: true,
    collection: 2024
  },
  {
    id: 12,
    name: "Anti-Theft Crossbody Bag",
    price: 129.99,
    size: "One Size",
    src: 'assets/w12.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2023
  },
  {
    id: 13,
    name: "Convertible Ballet Flats",
    price: 119.50,
    size: "US7.5",
    src: 'assets/w13.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 14,
    name: "Biodegradable Seamless Underwear",
    price: 24.99,
    size: "M",
    src: 'assets/w14.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: false,
    deal: true,
    collection: 2024
  },
  {
    id: 15,
    name: "Ceramic-Infused Blouse",
    price: 109.99,
    size: "S",
    src: 'assets/w15.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: false,
    collection: 2023
  },
  {
    id: 16,
    name: "Artisan Glass Bead Bracelet",
    price: 68.99,
    size: "Adjustable",
    src: 'assets/w16.webp',
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: true,
    collection: 2025
  },
  {
    id: 17,
    name: "Aromatherapy Linen Spray",
    price: 38.99,
    size: "4oz",
    src: 'assets/w17.webp',
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 18,
    name: "Smart Posture Correcting Camisole",
    price: 79.99,
    size: "L",
    src: 'assets/w18.webp',
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 19,
    name: "Convertible Travel Jumpsuit",
    price: 159.99,
    size: "8",
    src: 'assets/w19.webp',
    category: "women",
    discount: 60,
    new: false,
    trend: false,
    deal: true,
    collection: 2025
  },
  {
    id: 20,
    name: "Ethical Diamond Studs",
    price: 249.99,
    size: "One Size",
    src: 'assets/w20.webp',
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 21,
    name: "Heated Gloves",
    price: 89.99,
    size: "S/M",
    src: 'assets/w21.webp',
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 22,
    name: "Organic Linen Culotte Set",
    price: 179.99,
    size: "M",
    src: 'assets/w22.webp',
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2025
  },
  {
    id: 23,
    name: "Collapsible Travel Hat",
    price: 59.99,
    size: "One Size",
    src: 'assets/w23.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 24,
    name: "Biodegradable Mascara",
    price: 29.99,
    size: "0.3oz",
    src: 'assets/w24.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2023
  },
  {
    id: 25,
    name: "Adjustable Shapewear Bodysuit",
    price: 89.99,
    size: "L",
    src: 'assets/w25.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: false,
    deal: true,
    collection: 2025
  },
  {
    id: 26,
    name: "Artisan Block-Printed Scarf",
    price: 78.50,
    size: "Long",
    src: 'assets/w26.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 27,
    name: "Smart Yoga Bra",
    price: 69.99,
    size: "34C",
    src: 'assets/w27.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: false,
    collection: 2023
  },
  {
    id: 28,
    name: "Convertible Leather Backpack",
    price: 229.99,
    size: "20L",
    src: 'assets/w28.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: false,
    deal: true,
    collection: 2025
  },
  {
    id: 29,
    name: "Heated Massage Shawl",
    price: 139.99,
    size: "One Size",
    src: 'assets/w29.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 30,
    name: "Sustainable Sunglasses",
    price: 129.99,
    size: "One Size",
    src: 'assets/w30.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 31,
    name: "Silk Sleep Mask with Ear Plugs",
    price: 49.99,
    size: "One Size",
    src: 'assets/w31.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: false,
    deal: false,
    collection: 2025
  },
  {
    id: 32,
    name: "Crystal-Infused Facial Roller",
    price: 42.99,
    size: "One Size",
    src: 'assets/w32.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 33,
    name: "Customizable Birth Flower Jewelry Set",
    price: 98.99,
    size: "Adjustable",
    src: 'assets/w33.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: false,
    collection: 2023
  },
  {
    id: 34,
    name: "Self-Warming Leggings",
    price: 89.99,
    size: "M",
    src: 'assets/w34.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: false,
    deal: true,
    collection: 2025
  },
  {
    id: 35,
    name: "Handwoven Market Basket",
    price: 129.99,
    size: "Large",
    src: 'assets/w35.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 36,
    name: "Glow Therapy Face Mask",
    price: 59.99,
    size: "One Size",
    src: 'assets/w36.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 37,
    name: "Ethical Silk Robe",
    price: 149.99,
    size: "S/M",
    src: 'assets/w37.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: false,
    deal: false,
    collection: 2025
  },
  {
    id: 38,
    name: "Convertible Pearl Jewelry Set",
    price: 179.99,
    size: "Adjustable",
    src: 'assets/w38.webp',
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 39,
    name: "Aromatherapy Work Heels",
    price: 159.99,
    size: "US8.5",
    src: 'assets/w39.webp',
    category: "women",
    discount: 60,
    new: false,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 40,
    name: "Smart Fitness Tracker Leggings",
    price: 99.99,
    size: "L",
    src: 'assets/w40.webp',
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 41,
    name: "Sustainable Denim Jacket",
    price: 129.99,
    size: "M",
    src: 'assets/w41.webp',
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 42,
    name: "Luxury Faux Fur Coat",
    price: 249.99,
    size: "S",
    src: 'assets/w42.webp',
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2023
  },
  {
    id: 43,
    name: "Smart Travel Pillow",
    price: 49.99,
    size: "One Size",
    src: 'assets/w43.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 44,
    name: "Biodegradable Yoga Mat",
    price: 79.99,
    size: "One Size",
    src: 'assets/w44.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 45,
    name: "Artisan Handwoven Clutch",
    price: 89.99,
    size: "One Size",
    src: 'assets/w45.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 46,
    name: "Temperature-Controlled Blanket",
    price: 199.99,
    size: "One Size",
    src: 'assets/w46.webp',
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 47,
    name: "Convertible Maxi Dress",
    price: 129.99,
    size: "M",
    src: 'assets/w47.webp',
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 48,
    name: "Smart Water Bottle",
    price: 39.99,
    size: "24oz",
    src: 'assets/w48.webp',
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2023
  },
  {
    id: 49,
    name: "Luxury Silk Scarf",
    price: 89.99,
    size: "One Size",
    src: 'assets/w49.webp',
    category: "women",
    discount: 60,
    new: true,
    trend: false,
    deal: true,
    collection: 2025
  },
  {
    id: 50,
    name: "Smart Fitness Tracker Watch",
    price: 199.99,
    size: "One Size",
    src: 'assets/w50.webp',
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 51,
    name: "Graphene-Infused Performance Blazer",
    price: 289.99,
    size: "42R",
    src: 'assets/m1.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 52,
    name: "Auto-Tightening Smart Dress Shoes",
    price: 219.99,
    size: "US10.5",
    src: 'assets/m2.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 53,
    name: "Phase-Change Cooling Polo",
    price: 79.99,
    size: "L",
    src: 'assets/m3.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 54,
    name: "Carbon Fiber Travel Belt",
    price: 94.50,
    size: "38",
    src: 'assets/m4.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 55,
    name: "Holographic Minimalist Wallet",
    price: 69.99,
    size: "One Size",
    src: 'assets/m5.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 56,
    name: "Magnetic Convertible Cargo Pants",
    price: 124.99,
    size: "34x32",
    src: 'assets/m6.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 57,
    name: "Self-Cleaning Dress Shirt",
    price: 149.99,
    size: "16.5/35",
    src: 'assets/m7.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: false,
    deal: false,
    collection: 2023
  },
  {
    id: 58,
    name: "Titanium Dive Watch",
    price: 349.99,
    size: "One Size",
    src: 'assets/m8.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 59,
    name: "Heated Flannel Shacket",
    price: 179.99,
    size: "XL",
    src: 'assets/m9.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 60,
    name: "Odor-Destroying Performance Socks",
    price: 24.99,
    size: "10-13",
    src: 'assets/m10.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 61,
    name: "Modular Travel System Backpack",
    price: 229.99,
    size: "28L",
    src: 'assets/m11.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 62,
    name: "Laser-Measured Dress Belt",
    price: 89.99,
    size: "40",
    src: 'assets/m12.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 63,
    name: "Solar-Charged Expedition Jacket",
    price: 279.99,
    size: "L",
    src: 'assets/m13.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 64,
    name: "Anti-Fatigue Dress Shoes.",
    price: 189.99,
    size: "US11",
    src: 'assets/m14.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 65,
    name: "Quick-Dry Merino Suit",
    price: 499.99,
    size: "40L",
    src: 'assets/m15.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 66,
    name: "Titanium Eyewear System",
    price: 179.99,
    size: "One Size",
    src: 'assets/m16.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 67,
    name: "No-Iron Travel Dress Shirt",
    price: 119.99,
    size: "17/36",
    src: 'assets/m17.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 68,
    name: "Biometric Compression Shirt",
    price: 89.99,
    size: "M",
    src: 'assets/m18.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 69,
    name: "Portable Espresso System",
    price: 159.99,
    size: "One Size",
    src: 'assets/m19.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: false,
    deal: false,
    collection: 2023
  },
  {
    id: 70,
    name: "Aerodynamic Commuter Backpack",
    price: 169.99,
    size: "20L",
    src: 'assets/m20.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 71,
    name: "Self-Heating Shave Kit",
    price: 79.99,
    size: "One Size",
    src: 'assets/m21.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 72,
    name: "Recycled Ocean Plastic Sunglasses",
    price: 129.99,
    size: "One Size",
    src: 'assets/m22.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 73,
    name: "Temperature-Regulating Sleep Mask",
    price: 49.99,
    size: "One Size",
    src: 'assets/m23.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: false,
    deal: false,
    collection: 2024
  },
  {
    id: 74,
    name: "Tactical Dress Belt",
    price: 109.99,
    size: "38",
    src: 'assets/m24.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 75,
    name: "Smart Fitness Duffel",
    price: 199.99,
    size: "40L",
    src: 'assets/m25.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2023
  },
  {
    id: 76,
    name: "Self-Tying Dress Shoes",
    price: 249.99,
    size: "US10.5",
    src: 'assets/m26.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 77,
    name: "Portable Barbell Set",
    price: 179.99,
    size: "One Size",
    src: 'assets/m27.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: false,
    deal: false,
    collection: 2025
  },
  {
    id: 78,
    name: "Aerogel-Insulated Jacket",
    price: 299.99,
    size: "XL",
    src: 'assets/m28.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 79,
    name: "Biometric Smart Ring",
    price: 149.99,
    size: "Adjustable",
    src: 'assets/m29.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 80,
    name: "Magnetic Closure Work Boots",
    price: 159.99,
    size: "US12",
    src: 'assets/m30.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 81,
    name: "Convertible Travel Suit",
    price: 349.99,
    size: "44R",
    src: 'assets/m31.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: false,
    deal: false,
    collection: 2023
  },
  {
    id: 82,
    name: "Self-Cleaning Water Bottle",
    price: 59.99,
    size: "24oz",
    src: 'assets/m32.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 83,
    name: "Heated Massage Shirt",
    price: 119.99,
    size: "L",
    src: 'assets/m33.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 84,
    name: "Modular Briefcase System",
    price: 289.99,
    size: "One Size",
    src: 'assets/m34.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 85,
    name: "Anti-Gravity Suspension Jeans",
    price: 139.99,
    size: "36x34",
    src: 'assets/m35.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: false,
    deal: false,
    collection: 2024
  },
  {
    id: 86,
    name: "Smart Golf Belt",
    price: 129.99,
    size: "40",
    src: 'assets/m36.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 87,
    name: "Aerodynamic Swim Goggles",
    price: 79.99,
    size: "One Size",
    src: 'assets/m37.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2023
  },
  {
    id: 88,
    name: "Odor-Eliminating Dress Socks",
    price: 29.99,
    size: "10-13",
    src: 'assets/m38.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 89,
    name: "Foldable Electric Bike Helmet",
    price: 149.99,
    size: "One Size",
    src: 'assets/m39.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: false,
    deal: false,
    collection: 2025
  },
  {
    id: 90,
    name: "No-Iron Travel Blazer",
    price: 189.99,
    size: "42L",
    src: 'assets/m40.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 91,
    name: "Self-Cooling Undershirt",
    price: 49.99,
    size: "M",
    src: 'assets/m41.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 92,
    name: "Portable Espresso Maker",
    price: 129.99,
    size: "One Size",
    src: 'assets/m42.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 93,
    name: "Smart Dress Shirt Stayers",
    price: 39.99,
    size: "One Size",
    src: 'assets/m43.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: false,
    deal: false,
    collection: 2023
  },
  {
    id: 94,
    name: "Tactical Cargo Joggers",
    price: 89.99,
    size: "36x32",
    src: 'assets/m44.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 95,
    name: "Heated Insoles",
    price: 99.99,
    size: "US9-11",
    src: 'assets/m45.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 96,
    name: "Anti-Theft Travel Jeans",
    price: 119.99,
    size: "34x32",
    src: 'assets/m46.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 97,
    name: "Gravity-Infused Water Bottle",
    price: 49.99,
    size: "32oz",
    src: 'assets/m47.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: false,
    deal: false,
    collection: 2024
  },
  {
    id: 98,
    name: "Odor-Free Gym Bag",
    price: 79.99,
    size: "30L",
    src: 'assets/m48.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 99,
    name: "Solar-Charged Camping Tie",
    price: 64.99,
    size: "One Size",
    src: 'assets/m49.webp',
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2023
  },
  {
    id: 100,
    name: "Smart Resistance Bands",
    price: 89.99,
    size: "Set of 5",
    src: 'assets/m50.webp',
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 101,
    name: "Dinosaur Glow-in-the-Dark Pajama Set",
    price: 34.99,
    size: "4T",
    src: 'assets/k1.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: false,
    deal: true,
    collection: 2024
  },
  {
    id: 102,
    name: "Interactive Light-Up Sneakers",
    price: 45.50,
    size: "12C",
    src: 'assets/k2.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 103,
    name: "Space Explorer Backpack",
    price: 39.99,
    size: "One Size",
    src: 'assets/k3.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 104,
    name: "Animal Hooded Towel",
    price: 28.99,
    size: "5T",
    src: 'assets/k4.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: false,
    deal: true,
    collection: 2024
  },
  {
    id: 105,
    name: "Building Block Watch",
    price: 32.50,
    size: "Adjustable",
    src: 'assets/k5.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 106,
    name: "Magical Unicorn Raincoat",
    price: 49.99,
    size: "5T",
    src: 'assets/k6.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2023
  },
  {
    id: 107,
    name: "Robot Coding Toy Set",
    price: 59.99,
    size: "One Size",
    src: 'assets/k7.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2024
  },
  {
    id: 108,
    name: "Glow-in-the-Dark Constellation Sheets",
    price: 42.99,
    size: "Twin",
    src: 'assets/k8.webp',
    category: "kids",
    discount: 40,
    new: true,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 109,
    name: "3D Dinosaur Slippers",
    price: 27.99,
    size: "13C",
    src: 'assets/k9.webp',
    category: "kids",
    discount: 30,
    new: false,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 110,
    name: "Personalized Growth Chart Ruler",
    price: 35.50,
    size: "One Size",
    src: 'assets/k10.webp',
    category: "kids",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 111,
    name: "Underwater Camera Set",
    price: 54.99,
    size: "One Size",
    src: 'assets/k11.webp',
    category: "kids",
    discount: 30,
    new: false,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 112,
    name: "Bubble Machine Backpack",
    price: 39.99,
    size: "One Size",
    src: 'assets/k12.webp',
    category: "kids",
    discount: 40,
    new: true,
    trend: false,
    deal: false,
    collection: 2023
  },
  {
    id: 113,
    name: "Interactive Alphabet Rug",
    price: 47.99,
    size: "40x60in",
    src: 'assets/k13.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 114,
    name: "Solar System Planetarium Set",
    price: 52.50,
    size: "One Size",
    src: 'assets/k14.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 115,
    name: "No-Spill Paint Cups",
    price: 24.99,
    size: "Set of 6",
    src: 'assets/k15.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 116,
    name: "T-Rex Inflatable Costume",
    price: 59.99,
    size: "Ages 4-6",
    src: 'assets/k16.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 117,
    name: "Personalized Storybook Set",
    price: 42.99,
    size: "One Size",
    src: 'assets/k17.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 118,
    name: "Butterfly Wings Costume",
    price: 37.50,
    size: "3T",
    src: 'assets/k18.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 119,
    name: "Glow-in-the-Dark Play Tent",
    price: 64.99,
    size: "49x49x43in",
    src: 'assets/k19.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 120,
    name: "Personalized Step Stool",
    price: 39.99,
    size: "10in H",
    src: 'assets/k20.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 121,
    name: "Dinosaur Egg Sand Kit",
    price: 31.99,
    size: "One Size",
    src: 'assets/k21.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2023
  },
  {
    id: 122,
    name: "Personalized Growth Journal",
    price: 28.50,
    size: "One Size",
    src: 'assets/k22.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 123,
    name: "Waterproof Digital Watch",
    price: 34.99,
    size: "Adjustable",
    src: 'assets/k23.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 124,
    name: "Magic Sketch Board",
    price: 44.99,
    size: "12x9in",
    src: 'assets/k24.webp',
    category: "kids",
    discount: 40,
    new: true,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 125,
    name: "Balance Bike for Toddlers",
    price: 89.99,
    size: "12in Wheels",
    src: 'assets/k25.webp',
    category: "kids",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 126,
    name: "Personalized Name Puzzle",
    price: 36.99,
    size: "11x14in",
    src: 'assets/k26.webp',
    category: "kids",
    discount: 40,
    new: true,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 127,
    name: "Light-Up Dance Mat",
    price: 57.99,
    size: "35x35in",
    src: 'assets/k27.webp',
    category: "kids",
    discount: 30,
    new: false,
    trend: false,
    deal: false,
    collection: 2023
  },
  {
    id: 128,
    name: "3D Animal Face Mask Set",
    price: 19.99,
    size: "One Size",
    src: 'assets/k28.webp',
    category: "kids",
    discount: 40,
    new: true,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 129,
    name: "Personalized Growth Chart",
    price: 32.50,
    size: "6ft",
    src: 'assets/k29.webp',
    category: "kids",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 130,
    name: "Glow-in-the-Dark Constellations Set",
    price: 41.99,
    size: "One Size",
    src: 'assets/k30.webp',
    category: "kids",
    discount: 40,
    new: true,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 131,
    name: "No-Tie Shoelaces",
    price: 14.99,
    size: "Set of 3 Pairs",
    src: 'assets/k31.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 132,
    name: "Dino Dig Sandbox",
    price: 79.99,
    size: "36x24in",
    src: 'assets/k32.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 133,
    name: "Personalized Story Pillow",
    price: 45.99,
    size: "16x16in",
    src: 'assets/k33.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2023
  },
  {
    id: 134,
    name: "Interactive World Map",
    price: 59.50,
    size: "36x24in",
    src: 'assets/k34.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 135,
    name: "Rainbow Balance Stepping Stones",
    price: 52.99,
    size: "Set of 6",
    src: 'assets/k35.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 136,
    name: "Personalized Hair Accessory Organizer",
    price: 37.99,
    size: "12x6in",
    src: 'assets/k36.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 137,
    name: "Glow-in-the-Dark Jump Rope",
    price: 18.99,
    size: "7ft",
    src: 'assets/k37.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 138,
    name: "Personalized First Bike Helmet",
    price: 49.99,
    size: "50-54cm",
    src: 'assets/k38.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 139,
    name: "3D Solar System Mobile",
    price: 42.50,
    size: "36in Span",
    src: 'assets/k39.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2023
  },
  {
    id: 140,
    name: "Personalized Step Stool with Chalkboard",
    price: 44.99,
    size: "Two-Step",
    src: 'assets/k40.webp',
    category: "kids",
    discount: 40,
    new: false,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 141,
    name: "Glow-in-the-Dark Bath Toys",
    price: 22.99,
    size: "Set of 5",
    src: 'assets/k41.webp',
    category: "kids",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 142,
    name: "Personalized Growth Marker",
    price: 36.99,
    size: "24in",
    src: 'assets/k42.webp',
    category: "kids",
    discount: 40,
    new: true,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 143,
    name: "Magic Water Drawing Mat",
    price: 39.99,
    size: "23x17in",
    src: 'assets/k43.webp',
    category: "kids",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 144,
    name: "Personalized Library Book Bag",
    price: 28.99,
    size: "One Size",
    src: 'assets/k44.webp',
    category: "kids",
    discount: 40,
    new: true,
    trend: true,
    deal: true,
    collection: 2025
  },
  {
    id: 145,
    name: "Glow-in-the-Dark Space Stickers",
    price: 15.99,
    size: "200 Count",
    src: 'assets/k45.webp',
    category: "kids",
    discount: 30,
    new: false,
    trend: false,
    deal: false,
    collection: 2023
  },
  {
    id: 146,
    name: "Personalized Wooden Name Puzzle",
    price: 29.99,
    size: "12x8in",
    src: 'assets/k46.webp',
    category: "kids",
    discount: 40,
    new: true,
    trend: true,
    deal: true,
    collection: 2024
  },
  {
    id: 147,
    name: "Splash-Resistant Music Player",
    price: 49.99,
    size: "One Size",
    src: 'assets/k47.webp',
    category: "kids",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2025
  },
  {
    id: 148,
    name: "Personalized First Christmas Ornament",
    price: 32.50,
    size: "4in",
    src: 'assets/k48.webp',
    category: "kids",
    discount: 40,
    new: true,
    trend: false,
    deal: true,
    collection: 2023
  },
  {
    id: 149,
    name: "Glow-in-the-Dark Wall Decals",
    price: 24.99,
    size: "50 Count",
    src: 'assets/k49.webp',
    category: "kids",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2024
  },
  {
    id: 150,
    name: "Personalized Growth Chart Poster",
    price: 27.99,
    size: "24x36in",
    src: 'assets/k50.webp',
    category: "kids",
    discount: 40,
    new: true,
    trend: true,
    deal: true,
    collection: 2025
  }
];

function App(){
  return(
    <>
     <Routes>
      <Route path="/" element={
        <>
          <Suspense fallback={<div>Loading...</div>}>
            <Landing />
            <Discount />
            <Collection />
            <BestSeller />
            <Deal />
            <Product />
            <About />
            <Social />
          </Suspense>
        </>
      } />
      <Route path="/SignIU" element={
            <Suspense fallback={<div>Loading...</div>}>
              <SignIU />
            </Suspense>
          } />
      <Route path="/AllProducts" element={
            <Suspense fallback={<div>Loading...</div>}>
              <AllProducts Products= />
            </Suspense>
          } />
      <Route path="/AllProducts/:param" element={
            <Suspense fallback={<div>Loading...</div>}>
              <AllProducts />
            </Suspense>
          } />
      <Route path="/ProductDetail/:id" element={
            <Suspense fallback={<div>Loading...</div>}>
              <ProductDetail />
            </Suspense>
          } />
      <Route path="/Cart" element={
            <Suspense fallback={<div>Loading...</div>}>
              <Cart />
            </Suspense>
          } />
      <Route path="/Save" element={
            <Suspense fallback={<div>Loading...</div>}>
              <Save />
            </Suspense>
          } />
     </Routes>
    </>
  )
}

export default App;
