import React from 'react'
import { FaArrowRightLong } from "react-icons/fa6";
import Men from "../assets/discountMen.png";
import Women from "../assets/discountwomen.png";
import New from "../assets/discountNew.png";

const Products = [
  // Women's Clothing (1-50)
  {
    id: 1,
    name: "Celestial Chiffon Maxi Dress",
    price: 129.99,
    size: "S",
    src: img1,
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: true,
    collection: 2025,
    detail: "Flowing maxi dress with celestial constellation print that glows slightly in UV light. Made from lightweight chiffon with French seams and adjustable spaghetti straps. Perfect for summer weddings or evening events with its flattering empire waist design and layered skirt."
  },
  {
    id: 2,
    name: "Architectural Origami Blazer",
    price: 189.99,
    size: "M",
    src: img2,
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2024,
    detail: "Structured vegan leather blazer featuring geometric folds inspired by origami art. Reinforced shoulders create dramatic silhouette while hidden stretch panels allow movement. Includes removable brooch featuring the same folded design."
  },
  {
    id: 3,
    name: "Holographic Platform Chelsea Boots",
    price: 159.99,
    size: "US8",
    src: img3,
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2023,
    detail: "Color-shifting holographic boots with 2.5 inch wedge heel and molded rubber sole for all-day comfort. Stretch gussets at ankle allow easy wear while water-resistant treatment protects the high-shine finish."
  },
  {
    id: 4,
    name: "Bio-Glow Yoga Leggings",
    price: 89.99,
    size: "L",
    src: img4,
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2025,
    detail: "Performance leggings impregnated with bioluminescent algae that emits soft glow during workouts. High-waisted compression fabric contains skin-rejuvenating minerals. Includes hidden pocket large enough for smartphones."
  },
  {
    id: 5,
    name: "Quantum Cooling Scarf",
    price: 65.50,
    size: "One Size",
    src: img5,
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2024,
    detail: "Smart scarf with microphase-change material that actively regulates temperature. Works as both cooling wrap in heat and insulator in cold. Foldable into compact pouch and comes with UV protection rating of UPF 50+."
  },
  {
    id: 6,
    name: "Modular Convertible Backpack",
    price: 145.00,
    size: "One Size",
    src: img6,
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: true,
    collection: 2023,
    detail: "Interchangeable bag system that transforms from backpack to tote to crossbody via magnetic attachment points. Made from recycled ocean plastic with RFID-blocking pockets and waterproof zippers. Includes 3 color panels for customization."
  },
  {
    id: 7,
    name: "Ceramic-Infused Silk Blouse",
    price: 112.99,
    size: "M",
    src: img7,
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2025,
    detail: "Luxury silk blouse infused with ceramic nanoparticles that provide natural UV protection and thermal regulation. Features hidden button placket, French cuffs, and asymmetrical hem with laser-cut detailing."
  },
  {
    id: 8,
    name: "Pressure-Point Ballet Flats",
    price: 79.99,
    size: "US7",
    src: img8,
    category: "women",
    discount: 60,
    new: true,
    trend: false,
    deal: true,
    collection: 2024,
    detail: "Foot-friendly flats with built-in acupressure points in memory foam footbed. Vegan leather upper features elasticated sides for easy wear and padded collar. Reflective strips provide nighttime visibility."
  },
  {
    id: 9,
    name: "AI-Powered Posture Shirt",
    price: 97.50,
    size: "L",
    src: img9,
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2023,
    detail: "Smart camisole with embedded sensors that vibrate gently when detecting slouching. Washable design connects via Bluetooth to track posture metrics. Seamless knit fabric provides light compression and moisture-wicking."
  },
  {
    id: 10,
    name: "Telescopic Cocktail Ring",
    price: 225.99,
    size: "Adjustable",
    src: img10,
    category: "women",
    discount: 60,
    new: true,
    trend: false,
    deal: true,
    collection: 2025,
    detail: "Innovative jewelry piece that expands and contracts via hidden mechanism to fit all finger sizes. Features lab-grown sapphires set in recycled platinum. Gift box includes polishing cloth and lifetime adjustments."
  },
  {
    id: 11,
    name: "Photosynthetic Jumpsuit",
    price: 145.99,
    size: "S",
    src: img11,
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2024,
    detail: "Sustainable one-piece infused with living algae that converts sunlight into vitamin D for skin. Organic hemp fabric treated with plant-based water resistance. Modular design allows sleeve and leg length adjustment."
  },
  {
    id: 12,
    name: "Acoustic Noise-Canceling Hoodie",
    price: 139.99,
    size: "M",
    src: img12,
    category: "women",
    discount: 60,
    new: true,
    trend: false,
    deal: true,
    collection: 2023,
    detail: "High-tech hoodie with woven piezoelectric fibers that actively reduce ambient noise. Smart pockets charge phones via body heat. Adjustable fitted hood contains sound-dampening foam inserts."
  },
  {
    id: 13,
    name: "Ferrofluid Handbag",
    price: 199.99,
    size: "One Size",
    src: img13,
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2025,
    detail: "Interactive purse filled with magnetized ferrofluid that responds to movement with mesmerizing patterns. Sealed acrylic casing prevents leaks while allowing visual display. Durable frame includes standard inner compartments."
  },
  {
    id: 14,
    name: "Piezoelectric Rain Boots",
    price: 112.50,
    size: "US8",
    src: img14,
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: true,
    collection: 2024,
    detail: "Weatherproof boots that harvest energy from footsteps to power integrated LEDs lining the soles. Flexible rubber construction with traction grip and antimicrobial lining. Produces light patterns synchronized with walking rhythm."
  },
  {
    id: 15,
    name: "Memory Foam Kimono",
    price: 89.99,
    size: "L",
    src: img15,
    category: "women",
    discount: 30,
    new: false,
    trend: false,
    deal: false,
    collection: 2023,
    detail: "Revolutionary lounge wear made from shape-memory foam fabric that returns to preset folds when not worn. Lightweight viscose blend maintains temperature regulation. Packable into self-forming bundle for travel."
  },
  {
    id: 16,
    name: "Augmented Reality Blouse",
    price: 165.00,
    size: "M",
    src: img16,
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: true,
    collection: 2025,
    detail: "Interactive top with woven conductive threads that activate AR filters when paired with companion app. Six designs change at touch, including color patterns and animated effects. Machine washable with special detachable battery pack."
  },
  {
    id: 17,
    name: "Self-Cleaning Wool Coat",
    price: 249.99,
    size: "L",
    src: img17,
    category: "women",
    discount: 30,
    new: false,
    trend: false,
    deal: false,
    collection: 2024,
    detail: "Premium merino wool outerwear treated with nanotechnology that repels stains and odors. Water-repellent yet breathable construction maintains warmth. Hidden placket transforms collar shape from lapel to hood."
  },
  {
    id: 18,
    name: "Programmable LED Shawl",
    price: 98.50,
    size: "One Size",
    src: img18,
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: true,
    collection: 2023,
    detail: "Lightweight wrap embedded with hundreds of micro-LEDs controlled via smartphone app. Choose from animated patterns or upload custom designs. Water-resistant silk backing folds compactly. Includes portable charger."
  },
  {
    id: 19,
    name: "Bamboo Fiber Corset",
    price: 134.99,
    size: "S",
    src: img19,
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2025,
    detail: "Sustainable structured undergarment made from woven bamboo fibers with titanium boning. Natural antimicrobial properties prevent odor buildup while providing posture support. Adjustable lace-up back for customized shaping."
  },
  {
    id: 20,
    name: "Solar-Chargeable Fedora",
    price: 87.99,
    size: "One Size",
    src: img20,
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2024,
    detail: "Stylish wide-brim hat with flexible solar panels that charge devices via USB port hidden in the band. Water-repellent paper straw construction maintains shape in humid conditions. UPF 50+ sun protection."
  },
  {
    id: 21,
    name: "Phase-Change Gloves",
    price: 65.99,
    size: "M",
    src: img21,
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: true,
    collection: 2023,
    detail: "Smart touchscreen-compatible gloves with micro-encapsulated temperature-regulating material. Maintains ideal hand temperature from -5°C to 15°C. Reinforced fingertips provide durability without sacrificing sensitivity."
  },
  {
    id: 22,
    name: "Kaleidoscope Trench Coat",
    price: 197.50,
    size: "L",
    src: img22,
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: false,
    collection: 2025,
    detail: "Dramatic waterproof coat with rotating prism panels that create shifting color patterns as you move. Removable inner thermal liner adjusts for seasonal wear. Hidden hood stores in collar compartment."
  },
  {
    id: 23,
    name: "Fermented Silk Blouse",
    price: 115.99,
    size: "M",
    src: img23,
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: true,
    collection: 2024,
    detail: "Innovative garment colored using bacterial fermentation process creating unique organic patterns. Naturally antimicrobial fabric resists odors. Each piece develops subtle color changes when exposed to sunlight."
  },
  {
    id: 24,
    name: "Cartesian Coordinate Dress",
    price: 143.99,
    size: "S",
    src: img24,
    category: "women",
    discount: 60,
    new: false,
    trend: false,
    deal: true,
    collection: 2023,
    detail: "Mathematically precise dress constructed using geometric grid system that allows customized fit via adjustable tension points throughout its structure. Stretch tech fabric maintains form while allowing movement."
  },
  {
    id: 25,
    name: "Mycelium Leather Portfolio",
    price: 109.50,
    size: "One Size",
    src: img25,
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2025,
    detail: "Sustainable mushroom-derived leather organizer featuring built-in wireless charging pad and RFID protection. Grows more supple with use while maintaining structure. Includes pen loop and document compartments."
  },
  {
    id: 26,
    name: "Kinetic Energy Dress",
    price: 175.99,
    size: "M",
    src: img26,
    category: "women",
    discount: 60,
    new: false,
    trend: false,
    deal: true,
    collection: 2024,
    detail: "Evening gown with piezoelectric threads that harvest energy from movement to power subtle illuminating embroidery patterns. Three layers of tulle create floating silhouette while maintaining energy efficiency."
  },
  {
    id: 27,
    name: "Volcanic Ash Leggings",
    price: 89.99,
    size: "L",
    src: img27,
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2023,
    detail: "High-performance activewear infused with volcanic minerals providing natural infrared therapy. Graduated compression support with seamless construction eliminates chafing. Moisture-wicking fabric regulates temperature during workouts."
  },
  {
    id: 28,
    name: "Holographic Bucket Bag",
    price: 132.99,
    size: "One Size",
    src: img28,
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2025,
    detail: "Color-shifting handbag constructed from thousands of micro-prisms that refract light dynamically. Structured base maintains shape while soft leather top collapses when empty. Magnetic closure with protective lining."
  },
  {
    id: 29,
    name: "Programmable Perfume Bracelet",
    price: 88.50,
    size: "Adjustable",
    src: img29,
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2024,
    detail: "Smart jewelry containing micro-encapsulated scent pods that release fragrance when activated by body heat. Companion app controls intensity and custom blends. Hypoallergenic metal alloy suitable for sensitive skin."
  },
  {
    id: 30,
    name: "Thermal-Regulating Palazzo Pants",
    price: 112.99,
    size: "S",
    src: img30,
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2023,
    detail: "Wide-leg trousers made from NASA-inspired phase-change fabric that adjusts insulation based on environment. Hidden drawstring allows hem adjustment between ankle and floor length. Deep pockets maintain sleek silhouette."
  },
  {
    id: 31,
    name: "Chameleon Silk Scarf",
    price: 76.99,
    size: "One Size",
    src: img31,
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2025,
    detail: "Luxury accessory woven with photochromic threads that subtly change color in sunlight. Oversize dimensions allow multiple styling options from shawl to belt. Signature hand-rolled edges prevent fraying."
  },
  {
    id: 32,
    name: "Bionic Shapewear",
    price: 134.50,
    size: "M",
    src: img32,
    category: "women",
    discount: 60,
    new: false,
    trend: false,
    deal: true,
    collection: 2024,
    detail: "Medical-grade compression garment with proprioceptive bands that stimulate muscle activation. Seamless construction targets specific muscle groups while providing smoothing effect. Machine washable fabric maintains elasticity."
  },
  {
    id: 33,
    name: "Algorithmic Art Jacket",
    price: 187.99,
    size: "L",
    src: img33,
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2023,
    detail: "Limited edition outerwear featuring digital pattern generated by custom algorithm ensuring no two jackets are identical. Weatherproof shell with removable quilted lining. Patch pockets integrate seamlessly into design."
  },
  {
    id: 34,
    name: "Ferrofluid Clutch",
    price: 155.99,
    size: "One Size",
    src: img34,
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2025,
    detail: "Mesmerizing evening bag containing magnetized fluid that creates organic shapes when tilted. Shatterproof acrylic case with reinforced seams. Includes cleaning kit and spare ferrofluid capsules."
  },
  {
    id: 35,
    name: "Photosynthetic Cardigan",
    price: 98.99,
    size: "S",
    src: img35,
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2024,
    detail: "Living garment woven with photosynthetic yarn containing microalgae that produces oxygen. Lightweight merino wool blend responds to humidity changes. Biodegradable packaging includes care instructions."
  },
  {
    id: 36,
    name: "Topological Tote",
    price: 122.50,
    size: "One Size",
    src: img36,
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2023,
    detail: "Mathematically inspired handbag with Möbius strip construction creating continuous surface. Durable recycled polyester maintains structure while collapsing flat when empty. Water-resistant interior holds essentials securely."
  },
  {
    id: 37,
    name: "Piezoelectric Evening Gown",
    price: 299.99,
    size: "M",
    src: img37,
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2025,
    detail: "Red carpet-worthy dress with thousands of piezoelectric crystals that gather energy from movement to power integrated lighting systems. Customizable color patterns via app control. Detachable train converts to clutch."
  },
  {
    id: 38,
    name: "Memory Metal Choker",
    price: 89.99,
    size: "Adjustable",
    src: img38,
    category: "women",
    discount: 60,
    new: false,
    trend: false,
    deal: true,
    collection: 2024,
    detail: "Shape memory alloy jewelry that returns to preset form when heated. Can be molded into temporary artistic shapes then restored. Includes polishing paste to maintain luster."
  },
  {
    id: 39,
    name: "Carbon Fiber Yoga Mat",
    price: 145.00,
    size: "Standard",
    src: img39,
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2023,
    detail: "Ultra-lightweight yet rigid mat woven from carbon fiber strands that provide unmatched stability for balance poses. Micro-suction surface prevents slipping while integrated loops allow wall storage."
  },
  {
    id: 40,
    name: "Quantum Dot Scarf",
    price: 108.99,
    size: "Oversized",
    src: img40,
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2025,
    detail: "Nanotechnology accessory containing tiny semiconductors that emit different colors based on viewing angle. Ultra-fine silk wrap reflects light dynamically while maintaining softness. Comes with UV-protective storage pouch."
  },
  {
    id: 41,
    name: "Self-Repairing Leather Jacket",
    price: 345.99,
    size: "L",
    src: img41,
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2024,
    detail: "Premium vegan leather treated with micro-capsules that release healing compounds when scratched or scuffed. Ages beautifully while maintaining protection against elements. Removable shearling lining adjusts for seasonality."
  },
  {
    id: 42,
    name: "Electroluminescent Veil",
    price: 87.50,
    size: "One Size",
    src: img42,
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: true,
    collection: 2023,
    detail: "Ethereal fashion accessory woven with thin electroluminescent wires that glow softly when activated. Lightweight tulle material floats dramatically while powered by hidden battery pack with three intensity settings."
  },
  {
    id: 43,
    name: "Aerogel Heels",
    price: 199.99,
    size: "US8",
    src: img43,
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2025,
    detail: "Revolutionary light-as-air pumps constructed from aerospace-grade aerogel composite. Surprisingly durable despite featherlight feel. Memory foam footbed molds to foot shape over time while providing arch support."
  },
  {
    id: 44,
    name: "Chromatographic Blouse",
    price: 132.99,
    size: "M",
    src: img44,
    category: "women",
    discount: 60,
    new: true,
    trend: false,
    deal: true,
    collection: 2024,
    detail: "Artistic silk top infused with color-reactive compounds that subtly shift hues in response to pH changes from your skin. Unique to each wearer's chemistry. Dry clean only to preserve reactive properties."
  },
  {
    id: 45,
    name: "Gyroscopic Clutch",
    price: 178.50,
    size: "One Size",
    src: img45,
    category: "women",
    discount: 30,
    new: false,
    trend: true,
    deal: false,
    collection: 2023,
    detail: "Stabilized evening bag with internal gyroscope that keeps contents upright regardless of orientation. LED-lit interior makes finding items effortless. RFID-blocking compartment protects cards from scanning."
  },
  {
    id: 46,
    name: "Parametric Knit Sweater",
    price: 156.99,
    size: "S",
    src: img46,
    category: "women",
    discount: 60,
    new: true,
    trend: true,
    deal: true,
    collection: 2025,
    detail: "Computer-generated knitwear featuring mathematically optimized structure for perfect fit. Merino wool hollow fibers provide warmth without bulk. Organic shapes create visually striking negative space patterns."
  },
  {
    id: 47,
    name: "Phase-Change Lingerie Set",
    price: 115.99,
    size: "34B",
    src: img47,
    category: "women",
    discount: 30,
    new: true,
    trend: false,
    deal: false,
    collection: 2024,
    detail: "Intimate apparel with micro-encapsulated temperature-regulating material that responds to body heat. Seamless construction eliminates visible panty lines while providing lightweight support. Antibacterial lining prevents odors."
  },
  {
    id: 48,
    name: "Ferromagnetic Necklace",
    price: 165.50,
    size: "Adjustable",
    src: img48,
    category: "women",
    discount: 60,
    new: false,
    trend: true,
    deal: true,
    collection: 2023,
    detail: "Interactive jewelry featuring movable elements that respond to magnetic fields. Sterling silver chain suspends rare earth magnets that can be arranged in countless configurations. Includes storage pouch."
  },
  {
    id: 49,
    name: "Photosynthetic Shawl",
    price: 143.99,
    size: "Large",
    src: img49,
    category: "women",
    discount: 30,
    new: true,
    trend: true,
    deal: false,
    collection: 2025,
    detail: "Living wrap containing symbiotic algae that generates oxygen while worn. Organic cotton backing houses the biological system while remaining soft against skin. Self-contained ecosystem requires only occasional misting."
  },
  {
    id: 50,
    name: "Quantum Entanglement Studs",
    price: 225.99,
    size: "One Size",
    src: img50,
    category: "women",
    discount: 60,
    new: false,
    trend: false,
    deal: true,
    collection: 2024,
    detail: "Pair of minimalist earrings crafted from materials that maintain quantum connection - when one changes temperature, the other responds instantly despite distance. Platinum settings with conflict-free diamond accents."
  },

  
  {
    id: 51,
    name: "Graphene-Infused Blazer",
    price: 289.99,
    size: "42R",
    src: img51,
    category: "men",
    discount: 40,
    new: true,
    trend: false,
    deal: true,
    collection: 2023,
    detail: "Revolutionary smart jacket with graphene lining that conducts body heat evenly while maintaining breathability. Self-cleaning nanocoating repels stains and wrinkles. Includes hidden charging ports in discreet pockets."
  },
  {
    id: 52,
    name: "Self-Tightening Dress Shoes",
    price: 199.99,
    size: "US10",
    src: img52,
    category: "men",
    discount: 40,
    new: false,
    trend: true,
    deal: false,
    collection: 2024,
    detail: "Innovative Oxfords with micro-motors that automatically adjust fit throughout the day. Genuine leather upper with ventilated insole prevents overheating. Powered by kinetic energy harvesting system."
  },
  {
    id: 53,
    name: "Phase Change Polo",
    price: 78.99,
    size: "L",
    src: img53,
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: true,
    collection: 2025,
    detail: "Performance shirt that actively regulates temperature using NASA-inspired smart fabric. Moisture-wicking technology keeps you dry while structural design maintains sharp appearance untucked. UPF 50+ protection."
  },
  {
    id: 54,
    name: "Carbon Fiber Belt",
    price: 89.50,
    size: "36",
    src: img54,
    category: "men",
    discount: 40,
    new: false,
    trend: false,
    deal: true,
    collection: 2023,
    detail: "Ultralight yet incredibly strong belt constructed from aerospace-grade composite material. Buckle integrates bottle opener and hex wrench. Lifetime warranty against breakage."
  },
  {
    id: 55,
    name: "Holographic Wallet",
    price: 65.99,
    size: "One Size",
    src: img55,
    category: "men",
    discount: 40,
    new: true,
    trend: true,
    deal: false,
    collection: 2024,
    detail: "RFID-blocking wallet with dynamic holographic display that changes patterns with movement. Genuine leather exterior conceals titanium money clip and card organizer with quick-access mechanism."
  },
];


function Discount(){
    return(
        <>
        <div className="w-[100%] h-auto py-[5rem] max-[710px]:pt-[5rem] max-[710px]:pb-0 flex flex-row max-[710px]:flex-col max-[710px]:gap-[1rem] items-center justify-evenly">
            <section className='w-[25%] max-[890px]:w-[30%] max-[710px]:w-[50%] h-auto bg-gray-300 p-[1rem] max-[460px]:w-[70%] max-[320px]:w-[80%]'>
                <img className="h-[10rem] w-[100%] scale-105 rotate-x-5 -rotate-y-10" src={Men} alt="Men discount" />  
                <div className='pt-[0.65rem]'>
                <h1 className="font-bold text-2xl select-none">40% OFF</h1>
                <p className='font-semibold select-none'>MEN COLLECTION</p>
                <button className='group font-semibold hover:bg-gray-200 rounded-sm pr-[0.75rem] py-[0.3rem] cursor-pointer transition-all duration-700 ease-in-out delay-150 hover:pl-[0.3rem]'>Go To Collection <FaArrowRightLong className='inline group-hover:translate-x-2 hover:bg-gray-200 transition-all duration-700 ease-in-out delay-150'/></button>
                </div>
            </section>
            <section className='w-[25%] max-[890px]:w-[30%] h-auto bg-pink-500 p-[1rem] max-[710px]:w-[50%] max-[460px]:w-[70%] max-[320px]:w-[80%]'>
                <div className="pb-[0.65rem]">
                <h1 className="font-bold text-2xl select-none">60% OFF</h1>
                <p className='font-semibold select-none'>WOMEN COLLECTION</p>
                <button className='group font-semibold hover:bg-pink-400 rounded-sm pr-[0.75rem] py-[0.3rem] cursor-pointer transition-all duration-700 ease-in-out delay-150 hover:pl-[0.3rem]'>Go To Collection <FaArrowRightLong className='inline group-hover:translate-x-2 hover:bg-gray-200 transition-all duration-700 ease-in-out delay-150'/></button>
                </div>
                <img className="h-[10rem] w-[100%] scale-105 rotate-x-5 -rotate-y-10" src={Women} alt="Women Discount" />
            </section>
            <section className='w-[25%] max-[890px]:w-[30%] h-auto bg-yellow-300 p-[1rem] max-[710px]:w-[50%] max-[460px]:w-[70%] max-[320px]:w-[80%]'>
                <img className="h-[10rem] w-[100%] scale-105 rotate-x-5 -rotate-y-10" src={New} alt="New Discount" />
                <div className="pt-[0.65rem]">
                <h1 className="font-bold text-2xl select-none">30% OFF</h1>
                <p className='font-semibold select-none'>NEW COLLECTION</p>
                <button className='group font-semibold hover:bg-yellow-200 rounded-sm pr-[0.75rem] py-[0.3rem] cursor-pointer transition-all duration-700 ease-in-out delay-150 hover:pl-[0.3rem]'>Go To Collection <FaArrowRightLong className='inline group-hover:translate-x-2 hover:bg-gray-200 transition-all duration-700 ease-in-out delay-150'/></button>
                </div>
            </section>
        </div>
        </>
    );
}

export default Discount;